CREATE TABLE t_personal_user (
    personal_user_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    personal_user_name     VARCHAR2(100) NOT NULL,
    personal_user_email    VARCHAR2(100) NOT NULL UNIQUE,
    personal_user_telefone VARCHAR2(20),
    personal_user_cpf      VARCHAR2(14) NOT NULL UNIQUE,
    dth_create             DATE DEFAULT SYSDATE,
    dth_update             DATE DEFAULT SYSDATE,
    
    CONSTRAINT pk_personal_user PRIMARY KEY (personal_user_id) ENABLE
);

CREATE TABLE t_bank_user (
    bank_user_id           NUMBER GENERATED BY DEFAULT AS IDENTITY,
    bank_user_bank_cd      NUMBER NOT NULL,
    bank_user_agency_cd    VARCHAR2(10) NOT NULL,
    bank_user_account      VARCHAR2(20) NOT NULL,
    bank_user_account_type VARCHAR2(20) NOT NULL,
    dth_create             DATE DEFAULT SYSDATE,
    dth_update             DATE DEFAULT SYSDATE,

    CONSTRAINT pk_bank_user PRIMARY KEY (bank_user_id) ENABLE
);

CREATE TABLE t_user (
    user_id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_bank_id       NUMBER NOT NULL,
    user_personal_id   NUMBER NOT NULL,
    balance            NUMBER(15,2) DEFAULT 0,
    dth_create         DATE DEFAULT SYSDATE,
    dth_update         DATE DEFAULT SYSDATE,
    
    CONSTRAINT pk_user PRIMARY KEY (user_id) ENABLE,
    CONSTRAINT fk_user_bank FOREIGN KEY (user_bank_id)
        REFERENCES t_bank_user(bank_user_id),
    CONSTRAINT fk_user_personal FOREIGN KEY (user_personal_id)
        REFERENCES t_personal_user(personal_user_id)
);

CREATE TABLE t_investment (
    investment_id               NUMBER GENERATED BY DEFAULT AS IDENTITY,
    investment_name             VARCHAR2(100) NOT NULL,
    investment_type             VARCHAR2(50) NOT NULL,
    investment_min_value        NUMBER(15,2) DEFAULT 0,
    investment_profitability    NUMBER(5,2),
    investment_is_fgc_guarantee NUMBER(1) CHECK (investment_is_fgc_guarantee IN (0, 1)),
    investment_liquidity        VARCHAR2(50),
    dth_create                  DATE DEFAULT SYSDATE,
    dth_update                  DATE DEFAULT SYSDATE,

    CONSTRAINT pk_investment PRIMARY KEY (investment_id) ENABLE
);

CREATE TABLE t_user_investment (
    user_investment_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    investment_id       NUMBER NOT NULL,
    user_id             NUMBER NOT NULL,
    dth_create          DATE DEFAULT SYSDATE,
    dth_update          DATE DEFAULT SYSDATE,
    
    CONSTRAINT pk_user_investment PRIMARY KEY (user_investment_id) ENABLE,
    CONSTRAINT fk_ui_investment FOREIGN KEY (investment_id)
        REFERENCES t_investment(investment_id),
    CONSTRAINT fk_ui_user FOREIGN KEY (user_id)
        REFERENCES t_user(user_id)
);